In [1]:
import numpy as np


In [14]:
a = np.array([1,2,3,4,5])


#multidimensional arrays
a_mul = np.array([[[1,2,3,1],
                [4,5,6,1],
                [7,8,9,1]],
                  [[1,1,1,1],
                  [1,1,1,1],
                  [1,1,1,1]]])
print(a_mul.shape)
print(a_mul.ndim)
print(a_mul.size)
print(a_mul.dtype)

(2, 3, 4)
3
24
int32


In [21]:
a_diff = np.array([[1,2,3],
         [4, "5", 6],
         [7,8,9]], dtype = np.int32)
print(a_diff.dtype)
print(a_diff[0][0].dtype)

int32
int32


In [24]:
d = {'1': 'A'}
a_diff = np.array([[1,2,3],
         [4, d, 6],
         [7,8,9]])
print(a_diff.dtype)
print(type(a_diff[0][0]))

object
<class 'int'>


In [25]:
#array with defualt values
a = np.full((2,3,4), 9)
a

array([[[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]]])

In [27]:
a = np.zeros((10,5,2))
a

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [28]:
a = np.ones((2,1,3))
a

array([[[1., 1., 1.]],

       [[1., 1., 1.]]])

In [29]:
a = np.empty((2,2,2))
a

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [32]:
x_values = np.arange(0, 1000, 5)
print(x_values)



[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265
 270 275 280 285 290 295 300 305 310 315 320 325 330 335 340 345 350 355
 360 365 370 375 380 385 390 395 400 405 410 415 420 425 430 435 440 445
 450 455 460 465 470 475 480 485 490 495 500 505 510 515 520 525 530 535
 540 545 550 555 560 565 570 575 580 585 590 595 600 605 610 615 620 625
 630 635 640 645 650 655 660 665 670 675 680 685 690 695 700 705 710 715
 720 725 730 735 740 745 750 755 760 765 770 775 780 785 790 795 800 805
 810 815 820 825 830 835 840 845 850 855 860 865 870 875 880 885 890 895
 900 905 910 915 920 925 930 935 940 945 950 955 960 965 970 975 980 985
 990 995]


In [34]:
x_values = np.linspace(0,100,11)
x_values

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [35]:
print(np.nan)
print(np.inf)

nan
inf


In [38]:
print(np.isnan(np.sqrt(-1)))
print(np.isinf(np.array([10])/0))

True
[ True]


C:\Users\ishas\AppData\Local\Temp\ipykernel_23144\3338874168.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.isnan(np.sqrt(-1)))
C:\Users\ishas\AppData\Local\Temp\ipykernel_23144\3338874168.py:2: RuntimeWarning: divide by zero encountered in divide
  print(np.isinf(np.array([10])/0))


In [45]:
#Mathematical Operations
#l1 = [1,2,3,4,5]
#l2 = [6,7,8,9,0]
a1 = np.array([1,23])
a2 = np.array([[1,1],
             [2,1]])

#print(l1*5)
print(a2 *5)
#print(l1+l2)
print(a1*a2)
print(np.sin(a1))

[[ 5  5]
 [10  5]]
[[ 1 23]
 [ 2 23]]
[ 0.84147098 -0.8462204 ]


In [47]:
#Array methods
a1 = np.append(a1, [6,4,3])
a1 = np.insert(a1, 3, [78])

print(a1)

[ 1 23  6 78  4  3  6  4  3]


In [50]:
#0-row, 1 - col
print(np.delete(a2,0,0))

[[2 1]]


In [59]:
a3 = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]])
print(a3.reshape(2,6))
print(a3.reshape(12,1))
print(a3.reshape(12,))
a_reshaped = a3.reshape((6,2))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [64]:
a3.resize(2,6)
print(a3)
print(a3.flatten())
print(a3.ravel())

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [70]:
var1 = a3.flatten()
#returns a flattened copy of the array
var1[2]= 100
print(var1)
print(a3)

var = [v for v in a3.flat]
print(var)


[  1   2 100   4   5   6   7   8   9  10  11  12]
[[  1   2 100   4   5   6]
 [  7   8   9  10  11  12]]
[1, 2, 100, 4, 5, 6, 7, 8, 9, 10, 11, 12]


In [73]:
# returns a flattened view of the array itself
var1 = a3.ravel()
var1[2]= 100
print(var1)
print(a3)


[  1   2 100   4   5   6   7   8   9  10  11  12]
[[  1   2 100   4   5   6]
 [  7   8   9  10  11  12]]


In [83]:
print(a3.transpose())
print(a3.T)
print(a3.swapaxes(0,1))

[[  1   7]
 [  2   8]
 [100   9]
 [  4  10]
 [  5  11]
 [  6  12]]
[[  1   7]
 [  2   8]
 [100   9]
 [  4  10]
 [  5  11]
 [  6  12]]
[[  1   7]
 [  2   8]
 [100   9]
 [  4  10]
 [  5  11]
 [  6  12]]


In [89]:
#Splitting & Merging arrays
a5 = np.array([[1,2,3],
              [4,5,6]])
               
a6 = np.array([[7,8,9],
              [10,11,12]])

a7 = np.concatenate((a5,a6),axis = 0)
a7
               

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [93]:
a_stack = np.stack((a5,a6))
#stack adds new dimension
print(a_stack)
a_stack.shape

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


(2, 2, 3)

In [94]:
#hstack and vstack
a_hstack = np.hstack((a5,a6))
# same as a7 = np.concatenate((a5,a6),axis = 1)
a_hstack

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [95]:
a_vstack = np.vstack((a5,a6))
# same as a7 = np.concatenate((a5,a6),axis = 0)
a_vstack

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [109]:
#splitting arrays
print(np.split(a3,2,axis = 1))

[array([[  1,   2, 100],
       [  7,   8,   9]]), array([[ 4,  5,  6],
       [10, 11, 12]])]


In [110]:
#Aggregrate Functions
print(a3.min())
print(a3.max())
print(a3.mean())
print(a3.std())
print(a3.sum())
print(np.median(a3))

1
100
14.583333333333334
25.96298112484175
175
7.5


In [118]:
numbers = np.random.randint(90,100, size=(2,3,4))
print(numbers)

[[[96 91 91 95]
  [99 99 98 93]
  [95 92 93 94]]

 [[92 97 91 98]
  [90 94 92 93]
  [92 99 90 97]]]


In [120]:
numbers = np.random.binomial(10,p=0.5, size = (5,10))
numbers

array([[8, 3, 5, 5, 9, 4, 6, 5, 4, 6],
       [6, 4, 7, 5, 7, 6, 3, 6, 8, 5],
       [5, 5, 5, 9, 4, 7, 3, 4, 4, 3],
       [2, 5, 6, 5, 5, 3, 7, 4, 4, 7],
       [4, 7, 3, 5, 6, 7, 6, 4, 4, 5]])

In [121]:
numbers = np.random.normal(loc =170, scale=15, size = (5,10))
numbers

array([[169.75696954, 161.54345557, 140.84929746, 186.43424459,
        167.82309708, 177.67352636, 201.59292353, 167.521516  ,
        161.83355265, 156.9588567 ],
       [167.53312805, 180.41367855, 155.00628778, 145.51173376,
        168.72518231, 209.21806026, 180.14084061, 176.51705585,
        182.21702517, 169.88456885],
       [159.15413124, 140.08209698, 191.95287912, 183.45012508,
        143.5289155 , 147.67007912, 158.42008418, 136.2070149 ,
        165.26068971, 166.93649348],
       [208.55996442, 152.17568573, 151.14529398, 169.34558438,
        162.98932516, 175.33178236, 159.24840466, 170.80514277,
        194.42664599, 169.39759016],
       [164.7473232 , 169.95143999, 172.10142013, 156.84734102,
        186.63083884, 176.29262873, 154.81117472, 168.52694078,
        158.1725278 , 190.218223  ]])

In [122]:
numbers = np.random.choice([3,4,5,6], size= (2,3))
numbers

array([[5, 5, 4],
       [4, 5, 4]])

In [123]:
np.save('myarray.npy', a3)

In [124]:
a = np.load('myarray.npy')
a

array([[  1,   2, 100,   4,   5,   6],
       [  7,   8,   9,  10,  11,  12]])

In [125]:
np.savetxt('myarray.csv', a3, delimiter = ",")

In [126]:
a = np.loadtxt('myarray.csv', delimiter = ",")
a

array([[  1.,   2., 100.,   4.,   5.,   6.],
       [  7.,   8.,   9.,  10.,  11.,  12.]])